spring:
  profiles:
    group:
      local: local
      prod: prod
    default: prod
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always