spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 10..
            client-secret: GO..
            scope:
              - email
              - profile
jwt:
  issuer: ceskim493@naver.com
  secret_key: st..